apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
        environment: {{ .Values.environment }}
    spec:
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
      - image: {{ .Values.container.imageWithTag }}
        name: {{ .Values.container.name }}
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
        ports:
          - containerPort: {{ .Values.container.port }}
        env:
          - name: environment
            value: {{ .Values.environment }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.container.port }}
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}

